// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9lpvjwkRsoHNCIJA2UimR-l2uSctXCs',
    appId: '1:397341096369:web:5e543c4fab01a0ce412590',
    messagingSenderId: '397341096369',
    projectId: 'test-project-a11d7',
    authDomain: 'test-project-a11d7.firebaseapp.com',
    storageBucket: 'test-project-a11d7.appspot.com',
    measurementId: 'G-KHJZ2M7C7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaFPIPzQ49RGfNtgQo64OS1gbPKy8veJY',
    appId: '1:397341096369:android:f50834436ba55aa1412590',
    messagingSenderId: '397341096369',
    projectId: 'test-project-a11d7',
    storageBucket: 'test-project-a11d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDul5Ho-MYvepSbJwpApPT3JJsM8B41cQY',
    appId: '1:397341096369:ios:cf99c5cc56e11640412590',
    messagingSenderId: '397341096369',
    projectId: 'test-project-a11d7',
    storageBucket: 'test-project-a11d7.appspot.com',
    iosClientId: '397341096369-vg4dhg1geasr4i1l0dibridit5oh7r6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannertarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDul5Ho-MYvepSbJwpApPT3JJsM8B41cQY',
    appId: '1:397341096369:ios:7fb56431b5358495412590',
    messagingSenderId: '397341096369',
    projectId: 'test-project-a11d7',
    storageBucket: 'test-project-a11d7.appspot.com',
    iosClientId: '397341096369-lckkp2fa4h1tteu2orh3b47jeorqpiku.apps.googleusercontent.com',
    iosBundleId: 'com.example.planner.RunnerTests',
  );
}
